"""
Default configuration values for the Australian Property Investment Calculator.
"""

# Default financial parameters
DEFAULT_DEPOSIT_PERCENT = 0.10
DEFAULT_INTEREST_RATE = 0.06
DEFAULT_LOAN_TERM = 30
DEFAULT_PROPERTY_GROWTH_RATE = 0.03
DEFAULT_RENTAL_INFLATION_RATE = 0.025
DEFAULT_PROPERTY_EXPENSES_PERCENT = 0.01
DEFAULT_STOCK_RETURN_RATE = 0.07
DEFAULT_SALARY_GROWTH_RATE = 0.03
DEFAULT_UPFRONT_COSTS = 3000
DEFAULT_USE_AFFORDABILITY_SWITCH = False
DEFAULT_CASH_AVAILABLE = 150000
DEFAULT_MAX_BORROWING = 977000
DEFAULT_ALLOWED_LVR = 0.90
DEFAULT_INCLUDE_LMI_ABOVE_80_LVR = True

# Portfolio growth / serviceability defaults (Stage 1 scaffold)
DEFAULT_SERVICEABILITY_BUFFER_RATE = 0.03
DEFAULT_SERVICEABILITY_RATE_FLOOR = 0.09
DEFAULT_RENTAL_INCOME_HAIRCUT = 0.80
DEFAULT_BANK_EXPENSE_FLOOR_MONTHLY = 3000
DEFAULT_CASH_BUFFER_MONTHS = 6
DEFAULT_PORTFOLIO_REVIEW_FREQUENCY = "Yearly"
DEFAULT_BASE_INVESTMENT_PURCHASE_PRICE = 550000
DEFAULT_NEW_PURCHASE_GROSS_RENTAL_YIELD = 0.055
DEFAULT_NEW_PURCHASE_PRICE_GROWTH_RATE = 0.03

# Default property values
DEFAULT_BTL_PROPERTY_PRICE = 800000
DEFAULT_BTR_PROPERTY_PRICE = 600000
DEFAULT_RI_EQUIVALENT_PROPERTY_PRICE = 800000
DEFAULT_BTR_WEEKLY_RENTAL = 500
DEFAULT_YOUR_WEEKLY_RENT = 450

# Default income parameters
DEFAULT_ANNUAL_GROSS_INCOME = 100000

# UI Configuration
DEFAULT_ANALYSIS_YEARS = 30 
