"""
Default configuration values for the Australian Property Investment Calculator.
"""

# Default financial parameters
DEFAULT_DEPOSIT_PERCENT = 0.10
DEFAULT_INTEREST_RATE = 0.06
DEFAULT_LOAN_TERM = 30
DEFAULT_PROPERTY_GROWTH_RATE = 0.03
DEFAULT_RENTAL_INFLATION_RATE = 0.025
DEFAULT_PROPERTY_EXPENSES_PERCENT = 0.01
DEFAULT_STOCK_RETURN_RATE = 0.07
DEFAULT_SALARY_GROWTH_RATE = 0.03
DEFAULT_UPFRONT_COSTS = 3000
DEFAULT_USE_AFFORDABILITY_SWITCH = False
DEFAULT_CASH_AVAILABLE = 150000
DEFAULT_MAX_BORROWING = 977000
DEFAULT_ALLOWED_LVR = 0.90
DEFAULT_INCLUDE_LMI_ABOVE_80_LVR = True

# Portfolio growth / serviceability defaults (Stage 1 scaffold)
DEFAULT_SERVICEABILITY_BUFFER_RATE = 0.03
DEFAULT_SERVICEABILITY_RATE_FLOOR = 0.09
DEFAULT_RENTAL_INCOME_HAIRCUT = 0.80
DEFAULT_BANK_EXPENSE_FLOOR_MONTHLY = 3000
DEFAULT_CASH_BUFFER_MONTHS = 6
DEFAULT_PORTFOLIO_REVIEW_FREQUENCY = "Yearly"
DEFAULT_BASE_INVESTMENT_PURCHASE_PRICE = 550000
DEFAULT_NEW_PURCHASE_GROSS_RENTAL_YIELD = 0.055
DEFAULT_NEW_PURCHASE_PRICE_GROWTH_RATE = 0.03
DEFAULT_PORTFOLIO_ANNUAL_GROSS_INCOME = 120000
DEFAULT_PORTFOLIO_SALARY_GROWTH_RATE = 0.03
DEFAULT_PORTFOLIO_CURRENT_INTEREST_RATE = 0.06
DEFAULT_PORTFOLIO_NEW_LOAN_TERM = 30
DEFAULT_EXISTING_RENTAL_INCOME_WEEKLY = 0
DEFAULT_EXISTING_RENTAL_GROWTH_RATE = 0.025
DEFAULT_MONTHLY_LIVING_EXPENSES = 4000
DEFAULT_MONTHLY_EXPENSE_GROWTH_RATE = 0.025
DEFAULT_EXISTING_HOME_LOAN_BALANCE = 0
DEFAULT_EXISTING_HOME_LOAN_TERM_REMAINING = 25
DEFAULT_EXISTING_HOME_EQUITY = 0
DEFAULT_EXISTING_INVESTMENT_LOAN_BALANCE = 0
DEFAULT_EXISTING_INVESTMENT_LOAN_TERM_REMAINING = 25
DEFAULT_OTHER_MONTHLY_DEBT_COMMITMENTS = 0
DEFAULT_PORTFOLIO_STARTING_CASH = 150000
DEFAULT_PORTFOLIO_ALLOWED_LVR = 0.90
DEFAULT_PORTFOLIO_INCLUDE_LMI_ABOVE_80 = True
DEFAULT_PORTFOLIO_UPFRONT_COSTS_PER_PURCHASE = 3000
DEFAULT_AVERAGE_VACANCY_RATE = 0.0833
DEFAULT_USE_PROPERTY_MANAGER = True
DEFAULT_PROPERTY_MANAGEMENT_FEE_RATE = 0.06

# Default property values
DEFAULT_BTL_PROPERTY_PRICE = 800000
DEFAULT_BTR_PROPERTY_PRICE = 600000
DEFAULT_RI_EQUIVALENT_PROPERTY_PRICE = 800000
DEFAULT_BTR_WEEKLY_RENTAL = 500
DEFAULT_YOUR_WEEKLY_RENT = 450

# Default income parameters
DEFAULT_ANNUAL_GROSS_INCOME = 100000

# UI Configuration
DEFAULT_ANALYSIS_YEARS = 30 
